version: 2.1

jobs:
  build-learning-typescript:
    working_directory: ~/learning-typescript
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-typescript-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-typescript-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: build
          command: npm run build

  test-learning-typescript:
    working_directory: ~/learning-typescript
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-typescript-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-typescript-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: unit test
          command: npm run test
      - run:
          name: codecov
          command: npm run codecov

workflows:
  version: 2
  learning-typescript-workflow:
    jobs:
      - build-learning-typescript
      - test-learning-typescript:
          requires:
            - build-learning-typescript
